#!/bin/sh

# PROVIDE: DAEMON_NAME
# REQUIRE: DAEMON
# KEYWORD: nojail shutdown
. /etc/rc.subr

name="DAEMON_NAME"
pidfile="/var/run/${name}.pid"
required_files="/usr/local/etc/${name}.conf"
exec_directory="/usr/local/bin"

export pidfile=$pidfile
export conffile=$required_files

command="${exec_directory}/BINARY_NAME"
start_postcmd="${name}_limit"
DAEMON_NAME_limit() {
  pid=`cat ${pidfile}`
  rctl -a process:$pid:pcpu:deny=5
  rctl -l process:$pid
}

rcvar=${name}_enable
load_rc_config $name
run_rc_command "$1"
